#ifndef EG_IR_FlameLantern
#define EG_IR_FlameLantern

#define FLAME_LANTERN_SETTINGS_NUM_BITS 32
#define FLAME_LANTERN_SETTINGS_KHZ 34

#define FLAME_LANTERN_OFF 0xFFA25D
#define FLAME_LANTERN_ON 0xFFE21D

#define FLAME_LANTERN_FLAME 0xFFE01F
#define FLAME_LANTERN_LAMP 0xFF906F

#define FLAME_LANTERN_REPEAT 0xFFFFFFFF

#endif